ALTER TABLE public.admins
  ADD COLUMN IF NOT EXISTS email TEXT;

ALTER TABLE public.agents
  ADD COLUMN IF NOT EXISTS grade TEXT DEFAULT '총판',
  ADD COLUMN IF NOT EXISTS phone TEXT,
  ADD COLUMN IF NOT EXISTS email TEXT,
  ADD COLUMN IF NOT EXISTS bank_name TEXT,
  ADD COLUMN IF NOT EXISTS bank_account TEXT,
  ADD COLUMN IF NOT EXISTS bank_account_holder TEXT,
  ADD COLUMN IF NOT EXISTS commission_balance NUMERIC(20,4) NOT NULL DEFAULT 0;
