// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/balance" | "/admin/balance/member" | "/admin/balance/member-log" | "/admin/balance/partner" | "/admin/balance/partner-log" | "/admin/balance/withdraw" | "/admin/board" | "/admin/commissions" | "/admin/content" | "/admin/history" | "/admin/inquiry" | "/admin/login" | "/admin/members" | "/admin/members/[id]" | "/admin/members/logs" | "/admin/members/trades" | "/admin/message" | "/admin/notice" | "/admin/partners" | "/admin/popup" | "/admin/settings" | "/admin/settings/auto-comment" | "/admin/settings/coin-categories" | "/admin/settings/coin-symbols" | "/admin/settings/join-code" | "/admin/staking" | "/admin/staking/member" | "/admin/staking/member-log" | "/assets" | "/history" | "/login" | "/margin-info" | "/notice" | "/partner" | "/partner/login" | "/points" | "/profile" | "/qa" | "/settings" | "/signup" | "/staking" | "/support" | "/trade" | "/wallet"
type AppRouteHandlerRoutes = "/api/admin/content" | "/api/admin/futures/manage" | "/api/admin/notices" | "/api/admin/partners" | "/api/admin/staking/manage" | "/api/admin/wallet/manage" | "/api/auth/login" | "/api/futures/close" | "/api/futures/open" | "/api/futures/orders/cancel" | "/api/liquidate" | "/api/member-detail/[memberId]" | "/api/partner" | "/api/record-login" | "/api/signup" | "/api/staking/subscribe" | "/api/transfer" | "/api/wallet/deposit" | "/api/wallet/summary" | "/api/wallet/withdraw"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/admin/history" | "/partner"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/balance": {}
  "/admin/balance/member": {}
  "/admin/balance/member-log": {}
  "/admin/balance/partner": {}
  "/admin/balance/partner-log": {}
  "/admin/balance/withdraw": {}
  "/admin/board": {}
  "/admin/commissions": {}
  "/admin/content": {}
  "/admin/history": {}
  "/admin/inquiry": {}
  "/admin/login": {}
  "/admin/members": {}
  "/admin/members/[id]": { "id": string; }
  "/admin/members/logs": {}
  "/admin/members/trades": {}
  "/admin/message": {}
  "/admin/notice": {}
  "/admin/partners": {}
  "/admin/popup": {}
  "/admin/settings": {}
  "/admin/settings/auto-comment": {}
  "/admin/settings/coin-categories": {}
  "/admin/settings/coin-symbols": {}
  "/admin/settings/join-code": {}
  "/admin/staking": {}
  "/admin/staking/member": {}
  "/admin/staking/member-log": {}
  "/api/admin/content": {}
  "/api/admin/futures/manage": {}
  "/api/admin/notices": {}
  "/api/admin/partners": {}
  "/api/admin/staking/manage": {}
  "/api/admin/wallet/manage": {}
  "/api/auth/login": {}
  "/api/futures/close": {}
  "/api/futures/open": {}
  "/api/futures/orders/cancel": {}
  "/api/liquidate": {}
  "/api/member-detail/[memberId]": { "memberId": string; }
  "/api/partner": {}
  "/api/record-login": {}
  "/api/signup": {}
  "/api/staking/subscribe": {}
  "/api/transfer": {}
  "/api/wallet/deposit": {}
  "/api/wallet/summary": {}
  "/api/wallet/withdraw": {}
  "/assets": {}
  "/history": {}
  "/login": {}
  "/margin-info": {}
  "/notice": {}
  "/partner": {}
  "/partner/login": {}
  "/points": {}
  "/profile": {}
  "/qa": {}
  "/settings": {}
  "/signup": {}
  "/staking": {}
  "/support": {}
  "/trade": {}
  "/wallet": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/admin/history": never
  "/partner": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
