// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/admin/balance/member-log/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/balance/member-log">> = Specific
  const handler = {} as typeof import("../../../app/admin/balance/member-log/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/balance/member/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/balance/member">> = Specific
  const handler = {} as typeof import("../../../app/admin/balance/member/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/balance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/balance">> = Specific
  const handler = {} as typeof import("../../../app/admin/balance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/balance/partner-log/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/balance/partner-log">> = Specific
  const handler = {} as typeof import("../../../app/admin/balance/partner-log/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/balance/partner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/balance/partner">> = Specific
  const handler = {} as typeof import("../../../app/admin/balance/partner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/balance/withdraw/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/balance/withdraw">> = Specific
  const handler = {} as typeof import("../../../app/admin/balance/withdraw/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/board/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/board">> = Specific
  const handler = {} as typeof import("../../../app/admin/board/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/commissions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/commissions">> = Specific
  const handler = {} as typeof import("../../../app/admin/commissions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/content/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/content">> = Specific
  const handler = {} as typeof import("../../../app/admin/content/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/history">> = Specific
  const handler = {} as typeof import("../../../app/admin/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/inquiry/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/inquiry">> = Specific
  const handler = {} as typeof import("../../../app/admin/inquiry/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/login">> = Specific
  const handler = {} as typeof import("../../../app/admin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/members/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/members/[id]">> = Specific
  const handler = {} as typeof import("../../../app/admin/members/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/members/logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/members/logs">> = Specific
  const handler = {} as typeof import("../../../app/admin/members/logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/members/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/members">> = Specific
  const handler = {} as typeof import("../../../app/admin/members/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/members/trades/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/members/trades">> = Specific
  const handler = {} as typeof import("../../../app/admin/members/trades/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/message/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/message">> = Specific
  const handler = {} as typeof import("../../../app/admin/message/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/notice/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/notice">> = Specific
  const handler = {} as typeof import("../../../app/admin/notice/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/partners/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/partners">> = Specific
  const handler = {} as typeof import("../../../app/admin/partners/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/popup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/popup">> = Specific
  const handler = {} as typeof import("../../../app/admin/popup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/settings/auto-comment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings/auto-comment">> = Specific
  const handler = {} as typeof import("../../../app/admin/settings/auto-comment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/settings/coin-categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings/coin-categories">> = Specific
  const handler = {} as typeof import("../../../app/admin/settings/coin-categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/settings/coin-symbols/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings/coin-symbols">> = Specific
  const handler = {} as typeof import("../../../app/admin/settings/coin-symbols/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/settings/join-code/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings/join-code">> = Specific
  const handler = {} as typeof import("../../../app/admin/settings/join-code/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../../app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/staking/member-log/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/staking/member-log">> = Specific
  const handler = {} as typeof import("../../../app/admin/staking/member-log/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/staking/member/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/staking/member">> = Specific
  const handler = {} as typeof import("../../../app/admin/staking/member/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/staking/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/staking">> = Specific
  const handler = {} as typeof import("../../../app/admin/staking/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/assets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assets">> = Specific
  const handler = {} as typeof import("../../../app/assets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/history">> = Specific
  const handler = {} as typeof import("../../../app/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/margin-info/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/margin-info">> = Specific
  const handler = {} as typeof import("../../../app/margin-info/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/notice/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notice">> = Specific
  const handler = {} as typeof import("../../../app/notice/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/partner/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partner/login">> = Specific
  const handler = {} as typeof import("../../../app/partner/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/partner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partner">> = Specific
  const handler = {} as typeof import("../../../app/partner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/points/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/points">> = Specific
  const handler = {} as typeof import("../../../app/points/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../../app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/qa/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/qa">> = Specific
  const handler = {} as typeof import("../../../app/qa/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../../app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../../app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/staking/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staking">> = Specific
  const handler = {} as typeof import("../../../app/staking/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/support">> = Specific
  const handler = {} as typeof import("../../../app/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/trade/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/trade">> = Specific
  const handler = {} as typeof import("../../../app/trade/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/wallet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wallet">> = Specific
  const handler = {} as typeof import("../../../app/wallet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/content/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/content">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/content/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/futures/manage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/futures/manage">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/futures/manage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/notices/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/notices">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/notices/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/partners/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/partners">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/partners/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/staking/manage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/staking/manage">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/staking/manage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/wallet/manage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/wallet/manage">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/wallet/manage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/futures/close/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/futures/close">> = Specific
  const handler = {} as typeof import("../../../app/api/futures/close/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/futures/open/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/futures/open">> = Specific
  const handler = {} as typeof import("../../../app/api/futures/open/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/futures/orders/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/futures/orders/cancel">> = Specific
  const handler = {} as typeof import("../../../app/api/futures/orders/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/liquidate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/liquidate">> = Specific
  const handler = {} as typeof import("../../../app/api/liquidate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/member-detail/[memberId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/member-detail/[memberId]">> = Specific
  const handler = {} as typeof import("../../../app/api/member-detail/[memberId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/partner/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/partner">> = Specific
  const handler = {} as typeof import("../../../app/api/partner/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/record-login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/record-login">> = Specific
  const handler = {} as typeof import("../../../app/api/record-login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/signup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/signup">> = Specific
  const handler = {} as typeof import("../../../app/api/signup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/staking/subscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staking/subscribe">> = Specific
  const handler = {} as typeof import("../../../app/api/staking/subscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/transfer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/transfer">> = Specific
  const handler = {} as typeof import("../../../app/api/transfer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/wallet/deposit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wallet/deposit">> = Specific
  const handler = {} as typeof import("../../../app/api/wallet/deposit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/wallet/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wallet/summary">> = Specific
  const handler = {} as typeof import("../../../app/api/wallet/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/wallet/withdraw/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wallet/withdraw">> = Specific
  const handler = {} as typeof import("../../../app/api/wallet/withdraw/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/admin/history/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin/history">> = Specific
  const handler = {} as typeof import("../../../app/admin/history/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/partner/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/partner">> = Specific
  const handler = {} as typeof import("../../../app/partner/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
